import Head from 'next/head';
import React, {FC} from 'react';
import Nav from '../Nav/Nav';
import s from './Layout.module.css';

const Layout:FC = ({children}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className={s.root}>{children}</main>
    </>
  );
};
export default Layout;
