import Head from 'next/head';
import React, {FC} from 'react';
import Nav from '../Nav/Nav';
import s from './Layout.module.css';

const Layout:FC = ({children}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />

      <main className={s.root}>{children}</main>

      <footer className='font-light bg-gray-900'>
        <p className='text-center px-2 py-4 text-gray-500'>
          Copyright © {(new Date).getFullYear()}
          <a href='https://fernandezalfredo.com/'
            className='text-gray-200 ml-1 duration-150 hover:text-blue-700'
            target="_blank" rel="noreferrer">fernandezalfredo.com</a>
        </p>
      </footer>
    </>
  );
};
export default Layout;
